/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import derivda.CalculoDerivadas;
import integral.IntegralFuncao;
import javax.swing.JOptionPane;
import modelo.Funcao;
import modelo.FuncaoParser;
import util.ValidadorEntrada;
import view.DerivadaView;
import view.IntegralIndefinidaView;

/**
 *
 * @author natalle.santos
 */
public class PrincipalView extends javax.swing.JFrame {
    
        FuncaoParser parser = new FuncaoParser();
        CalculoDerivadas derivadas = new CalculoDerivadas();
        IntegralFuncao integrais = new IntegralFuncao();
        ValidadorEntrada validador = new ValidadorEntrada(parser);
        
        
        private String expressao = "";
          private Funcao funcao; 

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblTituloCalculoDerivada = new javax.swing.JLabel();
        lblInformarPolinomio = new javax.swing.JLabel();
        lblPonto = new javax.swing.JLabel();
        txtPonto = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnDerivada = new javax.swing.JButton();
        btnIntIndefinida = new javax.swing.JButton();
        btnIntDefinida = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloCalculoDerivada.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        lblTituloCalculoDerivada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCalculoDerivada.setText("CALCULAR DERIVADA DE UMA FUNÇÃO ");

        lblInformarPolinomio.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        lblInformarPolinomio.setForeground(new java.awt.Color(0, 153, 153));
        lblInformarPolinomio.setText("INFORME SEU POLINÔMIO");

        lblPonto.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        lblPonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPonto.setText("f (x)");

        txtPonto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalcular.setText("salvar");
        btnCalcular.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(0, 153, 153));
        lblResultado.setText("Resultado");
        lblResultado.setToolTipText("");

        txtResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        lblTitulo.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 153, 153));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calculadora de Derivadas e Integrais");

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setText("limpar");
        btnLimpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnDerivada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDerivada.setText("Derivada");
        btnDerivada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btnDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerivadaActionPerformed(evt);
            }
        });

        btnIntIndefinida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIntIndefinida.setText("Integral Indefinida");
        btnIntIndefinida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btnIntIndefinida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntIndefinidaActionPerformed(evt);
            }
        });

        btnIntDefinida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIntDefinida.setText("Integral Definida");
        btnIntDefinida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        btnIntDefinida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntDefinidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloCalculoDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInformarPolinomio, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnIntIndefinida, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnIntDefinida, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtResultado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lblPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(32, 32, 32)
                .addComponent(lblTituloCalculoDerivada)
                .addGap(18, 18, 18)
                .addComponent(lblInformarPolinomio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcular)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addComponent(lblResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntIndefinida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntDefinida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        // TODO add your handling code here:



    // Captura a entrada do usuário no campo de texto txtPonto
        expressao = txtPonto.getText();

    // Validação da entrada
    if (!validador.validarEntrada(expressao)) {
        JOptionPane.showMessageDialog(this, validador.obterMensagemErro(), "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

        this.funcao = parser.parse(expressao);
        txtResultado.setText(funcao.toString());
   
    
    
    }//GEN-LAST:event_btnCalcularActionPerformed
       public Funcao getFuncao() {
        return funcao;
    }
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
         txtPonto.setText("");
    txtResultado.setText("");
    
    // Redefine a variável expressao para uma string vazia
    expressao = "";
        
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerivadaActionPerformed
        // TODO add your handling code here:
        
        DerivadaView dview = new DerivadaView(this); // Passa a instância atual de PrincipalView
       
    
    // Torna a nova tela visível
        dview.setVisible(true);
    }//GEN-LAST:event_btnDerivadaActionPerformed

    private void btnIntIndefinidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntIndefinidaActionPerformed
        // TODO add your handling code here:
        IntegralIndefinidaView integralView = new IntegralIndefinidaView(this);
        
        integralView.setVisible(true);
       
       
    }//GEN-LAST:event_btnIntIndefinidaActionPerformed

    private void btnIntDefinidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntDefinidaActionPerformed
        // TODO add your handling code here:
        
        PrincipalView principal = new PrincipalView();
        IntegralDefinidaView integralView = new IntegralDefinidaView(principal);
        integralView.setVisible(true);
        
    }//GEN-LAST:event_btnIntDefinidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnDerivada;
    private javax.swing.JButton btnIntDefinida;
    private javax.swing.JButton btnIntIndefinida;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblInformarPolinomio;
    private javax.swing.JLabel lblPonto;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloCalculoDerivada;
    private javax.swing.JTextField txtPonto;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
